apiVersion: v1
kind: Secret
metadata:
  name: mqtt-to-influx-secret
  namespace: mqtt-to-influx
  labels:
    app: mqtt-to-influx
type: Opaque
data:
  BROKER_USER: ${MQTT_BROKER_USER}
  BROKER_PWD: ${MQTT_BROKER_PWD}
  INFLUXDB_V2_TOKEN: ${INFLUXDB_INIT_TOKEN}
  INFLUXDB_V2_ORG: ${INFLUXDB_INIT_ORG}
  INFLUX_BUCKET: ${INFLUXDB_INIT_BUCKET}
---
